language: php

php:
 - 5.6  

before_script:  
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'

script: 
- phpunit

matrix:
 allow_failures:
   - php: 5.6   
 fast_finish: true
