name: Saludos

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '¡Felicidades! Acabas de realizar tu primer contribución al proyecto'' first issue'
        pr-message: '¡Felicidades! Acabas de realizar tu primer contribución al proyecto'' first pr'
