name: PHP Syntax Checker

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.2
      with:
        dir: './app/'
